# .github/workflows/run-dbt-prod.yml
name: run_dbt_prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Set the working directory for all run commands in the job
defaults:
  run:
    working-directory: ./nyc_parking_violations

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      # We need to target the root requirements.txt since we are inside nyc_parking_violations
      run: |
        python -m pip install --upgrade pip
        if [ -f ../requirements.txt ]; then pip install -r ../requirements.txt; fi
        
    - name: Create data directory
      # Creates the data folder in the root directory relative to nyc_parking_violations
      run: mkdir -p ../data
      
    - name: Run dbt Prod
      run: |
        dbt debug
        dbt compile --target prod
        # Note: running dbt run here will require the source tables to exist in the DB
        # dbt run --target prod 
